---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags/'
    run_list:
      - recipe[unix_users_test::default]
    attributes:
