name             'unix_users'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures unix_users'
long_description 'Installs/Configures unix_users'
version          '0.1.0'