name             'users'
maintainer       'Chris Parkinson'
maintainer_email 'chris@parkie.ca'
license          'all_rights'
description      'Installs/Configures users'
long_description 'Installs/Configures users'
version          '0.1.0'